layout_spectrum: 0.7780117364367931
typography_spectrum: 0.6077930411766513
color:
  saturation: 0.008584466151948465
  brandStrength: 0.6781725383481694
  lightness: 0.00466715499509753
  brandColors:
    - '#FFFFFF'
    - '#161A1B'
    - '#765D47'
    - '#C6AD8E'
    - '#28A692'
  rhythmicContrast: 0.008325919515849782
title: ' '
purpose:
  - type: external
    url: 'https://itunes.apple.com/us/app/the-grid./id990744597?mt=8'
    label: Install the app
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: iOS
opengraph:
  image: null
  type: null
  appId: null
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FaEfpARsP8Fg%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DaEfpARsP8Fg&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FaEfpARsP8Fg%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: The Grid
          url: 'https://www.youtube.com/user/TheGridio'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: www.youtube.com
      keywords:
        - grid
        - duration
        - views
        - design
        - website
        - dansky
        - web
        - chrome
        - hangout
        - wes
      description: >-
        Meet your new AI web designer. 1. Hire her & get a free domain name. 2.
        Add content & wait a few seconds. 3. Click "redesign" until she crafts
        your website just right. She designed https://thegrid.io/
      inLanguage: en
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=aEfpARsP8Fg&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=aEfpARsP8Fg&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=aEfpARsP8Fg&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=aEfpARsP8Fg&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=aEfpARsP8Fg&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=aEfpARsP8Fg'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=aEfpARsP8Fg
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=aEfpARsP8Fg
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=aEfpARsP8Fg'
      title: 'The Grid, websites that design themselves'
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/02f1a22a-1618-40f5-b0d2-f3568aa80f2e.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/02f1a22a-1618-40f5-b0d2-f3568aa80f2e.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
url: 'https://ios.thegrid.io'
description: ''
github: true
