name: iOS
favicon: null
layout_spectrum: 0.5867836
typography_spectrum: 0.3607452
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: The Grid iOS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1F150F'
    - '#393A38'
    - '#AB3039'
    - '#CF4B53'
    - '#FFD0C5'
  brandStrength: 0.672043
  lightness: 0.3181699
  saturation: 0.62557
  rhythmicContrast: 0.3623956
purpose: []
