collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.62557
  lightness: 0.3181699
  brandStrength: 0.672043
  brandColors:
    - '#1F150F'
    - '#393A38'
    - '#AB3039'
    - '#CF4B53'
    - '#FFD0C5'
  rhythmicContrast: 0.3623956
typography_spectrum: 0.3607452
layout_spectrum: 0.5867836
name: iOS
