layout_spectrum: 0.39561216263570775
typography_spectrum: 0.8283490547304512
color:
  saturation: 0.8050895651986841
  brandStrength: 0.9664735921528559
  lightness: 0.7059498491129921
  brandColors:
    - '#6C6E58'
    - '#3E423A'
    - '#417378'
    - '#A4CFBE'
    - '#F4F7D9'
  rhythmicContrast: 0.3109971902023374
title: ' The Grid iOS App'
purpose:
  - type: external
    url: 'https://itunes.apple.com/us/app/the-grid./id990744597?mt=8'
    label: Install the app
  - type: external
    url: 'https://betas.to/gDgbspc9'
    label: Become a beta tester
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: iOS
opengraph:
  image: null
  type: null
  appId: null
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/3793c45f-d991-482a-8e51-256ab66fc474.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/3793c45f-d991-482a-8e51-256ab66fc474.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
url: 'https://ios.thegrid.io'
description: ''
github: true
