name: iOS
favicon: null
layout_spectrum: 0.20594
typography_spectrum: 0.37991
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: The Grid iOS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#444444'
    - '#33b6e6'
    - '#b0c939'
    - '#87daf6'
  brandStrength: 0.672043
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
